# Generated by Django 4.1.5 on 2023-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "co2e",
                    models.FloatField(
                        help_text="The Carbon Dioxide equivalent value.",
                        verbose_name="Carbon Dioxide Equivalent",
                    ),
                ),
                (
                    "scope",
                    models.PositiveIntegerField(
                        help_text="Scope.", verbose_name="Scope"
                    ),
                ),
                (
                    "category",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Category.",
                        null=True,
                        verbose_name="Category",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        choices=[
                            ("PERSONAL_TRAVEL", "Personal travel"),
                            ("AIR_TRAVEL", "Air travel"),
                            (
                                "PURCHASED_GOODS_AND_SERVICES",
                                "Purchased goods and services",
                            ),
                            ("ELECTRICITY", "Electricity"),
                        ],
                        help_text="The activity type of this emission.",
                        max_length=30,
                        verbose_name="Activity",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("GBP", "GBP"),
                            ("KILOMETRES", "KILOMETRES"),
                            ("KWH", "KWH"),
                            ("MILES", "MILES"),
                        ],
                        help_text="The unit of this emission.",
                        max_length=10,
                        verbose_name="Unit",
                    ),
                ),
            ],
        ),
    ]
